# Generated by Django 4.1.5 on 2023-01-23 18:39

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", apps.users.models.UserManager()),],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
